spring:
  application:
    name: online-library-system

  datasource:
    url: jdbc:mysql://localhost:3306/ONLINE_LIBRARY?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
